#To retreive from vehicle db
# GET http://localhost:3000/vehicle/TN39Y5680
# GET http://localhost:3000/vehicle/all

#To add in query database
# POST http://localhost:3000/query/
# Content-Type:application/json

# {"License": "TN39Y5681", 
# "time_stamp": "20/12/2022, 08:46:28 pm", 
# "Location": [11.0176, 76.9674],
#  "InDatabase": 1
#  }

# {   "License": "TN39Y5681",
#     "time_stamp":"19/12/2022, 8:00:22 pm",
#     "Location":[2234,30.089678567],
#      "InDatabase":0
# }

# to reterive from query db
# POST http://localhost:3000/query/queryplate
# Content-Type:application/json

# {   "License": "TN39Y5680"
# }

# POST http://localhost:3000/query/querylat
# Content-Type:application/json

# {   "Location":[2234,30.089678567]
# }

# POST http://localhost:3000/query/querydate
# Content-Type:application/json

# {   "Date":"19/12/2022"
# }
# GET http://localhost:3000/query/ HTTP/1.1

# POST http://localhost:3000/query/querydateAndLat
# Content-Type:application/json

# {   "Date":"19/12/2022",
#     "Location":[2234,30.089678567]
    
# }

#To query anything
POST http://localhost:3000/query/queryAny
Content-Type:application/json

{  "Color":"brown",
    "Type":"Convertible"
}